### ISSUE TITLE
Комментарий без обид

### ISSUE THREAD

**Issue by Mihail192** [BSUIRstudent/TRITPO_LAB2#1]
По описанию приложение выглядит достаточно юзабилити  и перспективным,. Единственным моментом, в котором хотелось бы увидеть улучшения, это конечно же интерфейс. Нынешний интерфейс выглядит прямиком из Windows 98, и никак не соотносится со стилем Windows 10, к-рая указана в системных требованиях.

**Comment by BSUIRstudent** [comment]
В папке с мокапами интерфейс сырой и будет изменяться
