### ISSUE TITLE
Комментарий к проекту TRITPO_LAB2

### ISSUE THREAD

**Issue by Eugenito** [BSUIRstudent/TRITPO_LAB2#2]
Данный продукт будет полезен и облегчит жизнь тем, кто ищет компьютерные комплектующий. Единственная вещь ,которая мне не понравилась , это бедность оформления интерфейса. Предложение: сделать оформление в красивых и  приятных цветовых решениях и так сказать обновить дизайн-составляющую.

**Comment by BSUIRstudent** [comment]
Спасибо за комментарий. В будущем будет добавлен цветной интерфейс
